baseURL: "https://elo-issam.netlify.app"
languageCode: "fr-fr"
title: "ELO Issam Portfolio"
theme: MonTemplatePortfolio

Paginate: 3
disqusShortname:
googleAnalytics:

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Veille
      title: Veille Technologique
      url: /veille
      weight: 1

params:
  title: "ELO Issam"
  description: Portfolio Issam
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Bonjour, Je suis"
    title: "Issam."
    subtitle: "D√©veloppeur Junior | √âtudiant BTS SIO option SLAM"
    content: "Passionn√© par les nouvelles technologies et  int√©ress√© par le d√©veloppement WEB et applicatif, je compte poursuivre mes √©tudes dans ce domaine."
    image: /images/hero.png
    button:
      enable: true
      name: "Mon CV"
      url: "/pdf/CV.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ELO-I
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/issaml/
      #customIcons:
       # - icon: /fav.png
       #   url: "https://example.com"

  # About
  about:
    enable: true
    title: "A propos"
    image: "/images/me.png"
    content: |-
      Actuellement √©tudiant au lyc√©e Saint-Michel √† Annecy, j'effectue un BTS SIO Option SLAM (Service Informatique aux Organisations option solutions logicielles et applications m√©tiers )

      J'ai obtenu un BAC professionnel SN RISC au lyc√©e Saint-Vincent-de-Paul √† Collonges-sous-Sal√®ve o√π j'ai d√©j√† effectu√© plusieurs stages en entreprises dans le domaine du r√©seau.

      J'apprends aujourd'hui la programmation Back-end en cours et en autodidacte.

    skills:
      enable: true
      title: "Les technologies que j'utilise r√©guli√®rement"
      items:
        - "HTML/CSS/JS"
        - "PHP"
        - "Symfony"
        - "C#/WPF/Xamarin"
        - "Python"
        - "MySQL"
        - "VS Code/PhpStorm"
        - "Github/Git"
        - "Laragon"

  # Experience
  experience:
    enable: true
    items:
      - job: "D√©velopeur Back-End Django"
        company: "Little Yes"
        companyUrl: "https://little-yes.com/"
        date: "Jan 2022 - Fev 2022"
        info:
          enable: true
          content: J'y √©tais en tant que stagiaire.
        content: |
          Durant le stage chez Little Yes j‚Äôai pu travailler mi-pr√©sentiel mi-distanciel, j‚Äôai appris des nouvelles m√©thodes de travail dans le code et de productivit√©.
          Ce que j‚Äôai fait en stage :
          -	Apprentissage et utilisation d‚Äôun nouveau Framework Django avec l‚Äôarchitecture MVT et la m√©thode CRUD
          -	Travaill√© dans un environnement Virtuel
          -	Utilisation de l‚Äôoutil de versioning git avec GitLab
          -	Utilisation du Code First, la base de donn√©es est g√©n√©r√©e en fonction du code
          -	Base CSS en reproduisant une page du site Nintendo

      - job: "D√©veloppeur Python"
        company: "Cosmecode"
        companyUrl: "https://www.cosmecode.com/"
        date: "May 2021 - Jun 2021"
        info:
          enable: true
          content: J'y √©tais en tant que stagiaire.
        content: |
          Durant le stage chez COSMECODE, j‚Äôai mis en pratique mon apprentissage orient√© objet et appris sur le fonctionnement d‚Äôune startup. J‚Äôai pu pratiquer pour la premi√®re fois le travail de d√©veloppeur en remote
          Ce que j‚Äôai fait en stage :
          -	Apprentissage de l‚Äôoutil de versioning git avec GitHub
          -	La r√©alisation d‚Äôalgorithme pour scrappez des donn√©es avec l‚Äôutilisation du Framework scrappy en python
          -	La gestion d‚Äôun meeting,
          -	Contribution √† l‚Äôam√©lioration de l‚Äôentreprise gr√¢ce √† des remarques pertinentes

      - job: "Employ√© polyvalent "
        company: "McDonalds"
        companyUrl: "https://www.mcdonalds.fr/"
        date: "Nov 2019 - Avr 2022"
        info:
          enable: true
          content: Travail √† temps partiel en jour par semaine.
        content: |
          Employ√© polyvalent chez McDonald's.
          J'ai pu gr√¢ce √† ce job √©tudiant 
          - Apprendre √† g√©rer mon stress m√™me pendant les gros rush,
          - D√©velopper le travail d'√©quipe et l'entraide,
          - Et d√©velopper mon sens des relations humaines.

      - job: "Stagiare dans le service informatique de la mairie "
        company: "Mairie de Ferney-Voltaire"
        companyUrl: "https://www.ferney-voltaire.fr/"
        date: "Nov 2019 - Dec 2019"
        info:
          enable: true
          content: j'y √©tait en tant que stagiaire.
        content: |
          Stage de 4 semaines ‚Äì Dans le service Informatique √† la Mairie de Ferney-Voltaire
          Au cours de ce stage au sein de la Mairie de Ferney-Voltaire,
          J'ai pu r√©aliser des missions telles que : 
            - √âtude des besoins de la Mairie
            - Mise en place de solutions
            - R√©daction des analyses et des comptes rendus des projets
            - R√©daction des proc√©dures li√©es aux solutions
            - D√©ploiement de nouveaux postes au sein d'un nouvel environnement
            - Formation des utilisateurs
            - Support niveau 1 et 2
            - Veille technologique
            - Assistance pour les r√©ponses aux appels d'offres
            - D√©couvrir le r√©seau de la ville et les contraintes qu'il impose.

      - job: "Stagiaire en r√©seau informatiqueStagiaire "
        company: "Cogestra-Laser SA"
        companyUrl: "https://www.cogestra.ch/"
        date: "Jan 2019 - F√©v 2019"
        info:
          enable: true
          content: j'y √©tait en tant que stagiaire.
        content: |
          Un total de Stage de 8 semaines ( 2 fois 4 semaines)
          Durant ces 2 stages de 4 semaines:
          - J'ai pu effectuer des d√©pannages aux domiciles des clients en autonomie,
          - R√©aliser des devis pour des particuliers et entreprises,
          - Prendre en charge par moments les clients de la boutique,
          - R√©pondre √† des mails de clients,
          - Monter plusieurs dizaines de tours pour de grand Organisme (CERN, OMS...) Ou des particuliers,
          - Manipuler un serveur rack, d√©monter certaines parties, le configurer (Configuration du RAID et installation de Windows Serveur 2019),
          - Mettre en place un petit serveur DHCP et AD pour mettre en pratique mes connaissances,

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "BTS SIO option SLAM"
        school:
          name: "Saint Michel Annecy"
          url: "https://www.st-michel.fr/"
        date: "2020 - 2022"
        content: |-
          üíª D√©veloppement:
            - üî∂ Programmation 
              - üî∏ Applications Windows: C# (Windows Forms et console)
              - üî∏ Algorithmie : Python 
              - üî∏ Environnement : Visual Studio | Suite Jetbrains et WampServer | Laragon
            - üî∂ Syst√®me de Gestion de Bases de Donn√©es:
              - üî∏ MySQL : installation et configuration
              - üî∏ SQLServer : installation et configuration
              - üî∏ Requ√™tes SQL (requ√™tes simples, sous requ√™tes, jointure, groupement)
            - üî∂ Mod√©lisation
              - üî∏ Merise (Mod√®le Conceptuel de Donn√©es et mod√®le relationnel)
              - üî∏ U.M.L. (diagramme de classes et de s√©quence)
              - üî∏ Use Case

      - title: "Baccalaur√©at professionnel syst√®mes √©lectroniques num√©riques"
        school:
          name: "Lyc√©e Professionnel Saint Vincent de Paul"
          url: "https://www.saint-vincent74.fr/"
        date: "2017 - 2020"
        content: |-
          Comp√©tences acquises :
          - üîπ Administration syst√®me et Administration des r√©seaux
          - üîπ Excellente connaissance de l‚Äôenvironnement Microsoft (Server 2012 r2/2016/2019/, Windows 10, Windows 7)
          - üîπ Excellente connaissance de l‚Äôenvironnement CISCO ( Switch, Routeur configuration Console, Vlan etc.) 
          - üîπ Connaissance r√©seaux : TCP\IP, DHCP, DNS, SMB, NAT, POP, IMAP, SMTP, SSL, TLS
          - üîπ Annuaire Active Directory, des GPO, de IIS, Suite Office.
          - üîπ Connaissance sur les environnements : Vmware, VirtualBox, Tse
          - üîπ Mise en place de Script Powershell

  # Achievements
  achievements:
    enable: true
    items:
      - title: Certification Pix
        content: Certification Obligatoire pour les BTS pour √©valuer ces comp√©tences num√©riques
        url: /pdf/attestation-pix.pdf

      - title: MOOC L'Atelier RGPD
        content: CNIL - Commission Nationale de l'Informatique et des Libert√©s
        url: https://atelier-rgpd.cnil.fr/apprenant/default.php

      - title: MOOC SecNumacad√©mie
        content: ANSSI - Agence nationale de la s√©curit√© des syst√®mes d'information
        url: /pdf/attestation_secnumacademie.pdf

      - title: Formation "D√©veloppeur Web"
        content: Les bases du d√©veloppement WEB (HTML, CSS, JS, PHP, SQL, Git, symfony, React.js, ...)
        url: https://grafikart.fr/cursus

  # projects
  projects:
    enable: true
    items:
      - title: Portfolio Hugo
        content: R√©alisation du portfolio elo-issam.netlify.app avec un template hugo
        image: /images/projects/portfolio.png
        links :
          - icon: fab fa-github
            url: 


      - title: Projet Gustave Courbet
        content: R√©alisation d'un site web pour un mus√©e dans le cadre de l'Atelier professionnel la premi√®re ann√©e du BTS
        image: /images/projects/courbet.gif
        links :
          - icon: fab fa-github
            url: 

      - title: Projet site vitrine LSR Games
        content: R√©alisation d'un site web pour un escape game dans le cadre de l'professionnel la deuxi√®me ann√©e du BTS
        image: /images/projects/converter.jpg
        links :
          - icon: fab fa-github
            url: https://github.com/ELO-I/AP-SIO2_LSRGames


  #Contact
  contact:
    enable: true
    content: N'h√©sitez pas √† me contacter pour toutes questions ou offres je suis disponible pour y r√©pondre :)
    email: issam.el.ouiazzani@gmail.com
    btnName: Contactez moi

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/ELO-I
      linkedin: https://www.linkedin.com/in/issaml/
